# Generated by Django 3.0.6 on 2020-07-12 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdf', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='degree',
            new_name='college_name',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='school',
            new_name='college_university',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='university',
            new_name='company_exp1',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='previous_work',
        ),
        migrations.AddField(
            model_name='profile',
            name='college_pass_year',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='college_percentage',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='company_desc1',
            field=models.CharField(default=0, max_length=10000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='company_desc2',
            field=models.CharField(default=0, max_length=10000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='company_exp2',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='company_name1',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='company_name2',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='degree_college_name',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='degree_course',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='degree_pass_year',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='degree_percentage',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='degree_university',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='dob',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='father_name',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='gender',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='language',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='nationality',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='school_name',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='school_pass_year',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='school_percentage',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='school_university',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
    ]
