from django.db import models

# Create your models here.
class Profile(models.Model):
    name = models.CharField(max_length=200)
    father_name = models.CharField(max_length=200)
    gender = models.CharField(max_length=200)
    dob = models.CharField(max_length=200)
    nationality = models.CharField(max_length=200)
    language = models.CharField(max_length=200)
    email = models.CharField(max_length=200)
    phone = models.CharField(max_length=200)
    summary = models.TextField(max_length=2000)
    company_name1 = models.CharField(max_length=200)
    company_exp1 = models.CharField(max_length=200)
    company_desc1 = models.CharField(max_length=10000)
    company_name2 = models.CharField(max_length=200)
    company_exp2 = models.CharField(max_length=200)
    company_desc2 = models.CharField(max_length=10000)
    degree_course = models.CharField(max_length=200)
    degree_university = models.CharField(max_length=200)
    degree_college_name = models.CharField(max_length=200)
    degree_percentage = models.FloatField()
    degree_pass_year = models.IntegerField()
    college_name = models.CharField(max_length=200)
    college_university = models.CharField(max_length=200)
    college_pass_year = models.IntegerField()
    college_percentage = models.FloatField()
    school_name = models.CharField(max_length=200)
    school_university = models.CharField(max_length=200)
    school_pass_year = models.IntegerField()
    school_percentage = models.FloatField()
    skills = models.TextField(max_length=1000)